package pages;

import org.openqa.selenium.By;

public class CQLWorkspacepage {
	
	public static By tabCQLWorkspace = By.xpath("//div[contains(text(),'CQL Workspace')]");
	public static By lnkValueSets = By.id("valueSetLabel_Label");
	public static By txtoidId=By.xpath("//label[@title='OID']//following::input[1]");
	public static By codeurl = By.xpath("//label[@title='Code URL']//following::input[1]");
	public static By btnRetVS=By.xpath("//*[@id='searchPanel_VerticalPanel']/div[2]/table[1]/tbody/tr/td/table/tbody/tr[4]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/button");
	public static By btnApply = By.xpath("//*[@title='Apply']");
	public static By lnkDefinition = By.xpath("//span[contains(text(),'Definition')]");
	public static By inserticon=By.xpath("//button[@title='Insert']");
	public static By selectattribute=By.xpath("//Select[@id='availableItemToInsert_ListBox']");
	public static By dropdownAttributeDatatype = By.xpath("//select[@id='DataTypeBtAtrr_listBox']");
	public static By attributename=By.xpath("//select[@id='Atrr_listBox']");
	public static By btnCancelInsertOptionsAttributes=By.xpath("//button[@id='Cancel_button']");
	public static By closeicon = By.xpath("(//button[@class='close' ])[2]");
	public static By CrtDefinition = By.xpath("//*[@id='defineLabel_Label']");
	public static By definitionNameTxt = By.xpath("//*[@id='defineNameField']");
	public static By definitionSaveBtn = By.xpath("//button[@id='saveButton_definition']");
	public static By definitionSelectFirst = By.xpath("//*[@id='defineListBox']/option[1]");
	public static By definitionBuildCQLCode = By.xpath("//textarea[@title='CQL Expression Editor']");
	public static By definitionSelectSecond = By.xpath("//*[@id='defineListBox']/option[2]");
	public static By lnkFunction = By.xpath("//a[contains(.,'Function')]");
	public static By functionname = By.xpath("//input[@id='FunctionNameField']");
    public static By population_radio_btn = By.xpath("//input[@name='Population']");
    public static By addargument = By.xpath("//button[@id='Add_Argument_ID']");
	public static By argumentname = By.xpath("//input[@id='inputArgumentName']");
	public static By argument_available_datatype = By.xpath("//select[@id='listDataType']");
	public static By btn_argument_add = By.xpath("//button[@class='btn btn-primary btn-sm']");
	public static By functionBuildCQLCode = By.xpath("(//textarea[@class='ace_text-input'])[1]");
	public static By functionsavebtn = By.xpath("//button[@id='saveButton_function']");
	public static By txtFuncName=By.id("FunctionNameField");
	public static By txtFuncdesc=By.xpath("//textarea[@title='CQL Expression Editor']");
	public static By iconSave=By.xpath("(//button[@title='Save'])[2]");
	public static By iconSavedefinition=By.xpath("//button[@id='saveButton_definition']");
	public static By iconSave1=By.xpath("//button[@id='saveButton_function']");
	public static By txtDefiName=By.xpath("//input[@title='Enter Definition Name Required']");
	public static By txtDefidesc=By.xpath("//textarea[@title='CQL Expression Editor']");
	public static By lnkPara=By.id("paramLabel_Label");
	public static By txtParameterName=By.xpath("//input[@title='Enter Parameter Name Required']");
	public static By txtParadesc=By.xpath("//textarea[@title='CQL Expression Editor']");
	public static By txtSuffixCode=By.xpath("//input[@id='suffixInput_TextBox']");
	public static By lnkAddNew=By.xpath("//button[@id='Add_New_ID']");
	public static By lnkCodes=By.xpath("//span[@id='codesLabel_Label']");
	public static By txtCodeId=By.xpath("//input[@title='Enter the Code URL']"); 
	public static By btnRetrieve =By.xpath("//button[@title='Retrieve Code']");
	public static By chkboxTopCopyPasteCode=By.xpath("//table[@id='AppliedCodeTable']/tbody[1]/tr[1]/td[8]/div/table/tbody/tr/td/input");
	public static By lnkCopyCode=By.id("copyButton_codes");
	public static By lnkPasteCode=By.id("pasteButton_codes");
	public static By btnSaveDefi=By.id("saveButton_definition");
	public static By btnDelTopCode=By.xpath("//table[@id='AppliedCodeTable']/tbody[1]/tr[1]/td[6]//button");
	public static By iconInfo=By.xpath("//button[@aria-label='Click to view available short cut keys information']");
	public static By lnkGeneralInfo=By.xpath("//li[@id='generatalInformation_Anchor']/a");
	public static By headerGenInfo=By.xpath("//table[@id='generalInfoMainHPanel_HPanel']/tbody/tr//table/tbody/tr[1]//b");
	public static By lnkIncludes=By.id("includesLabel_Label");
	public static By headerIncludes=By.xpath("//table[@id='vPanel_VerticalPanelIncludeSection']/tbody/tr[1]/td//h4/b");
	public static By headerValueSets=By.xpath("//table[@id='vPanel_VerticalPanel']/tbody/tr[1]/td//h4/b");
	public static By headerCodes=By.xpath("//table[@id='vPanel_VerticalPanel']/tbody/tr[1]/td//h4/b");
	public static By headerParameter=By.xpath("//div[@id='mainParamViewVerticalPanel']/table/tbody//td/table/tbody/tr[1]/td//h4/b");
	public static By headerDefinition=By.xpath("//div[@id='mainDefViewVerticalPanel']/table/tbody//table/tbody/tr[1]/td//h4/b");
	public static By headerFunctions=By.xpath("//div[@id='mainFuncViewVerticalPanel']/table/tbody//table/tbody/tr[1]/td//h4/b");
	public static By lnkViewCQL=By.xpath("//*[@id='functionViewCQL_panel']");  //li[@id='viewCQL_Anchor']/a"]
	public static By headerViewCQL=By.xpath("//table[@id='cqlViewCQL_Id']/tbody/tr[1]/td//h4/b");
	public static By msgCodesMeasure=By.xpath("//table[@id='CQLWorkspaceView.containerPanel']//div[@id='WarningMessage']/div/b");
	public static By btnUpdateFromVSAC=By.id("updateVsacButton_Button");
	public static By successfulyupdatesymbal = By.xpath("//img[@title='Value set is updated from VSAC.']");
	public static By nameTopValueSet=By.xpath("//table[@id='AppliedQDMTable']//tbody[1]//tr[1]/td[1]//span");
	public static By editTopValueSet=By.xpath("//*[@id='AppliedQDMTable']/tbody[1]/tr/td[5]/div/table/tbody/tr/td/button");
	public static By txtCommentArea = By.xpath("//*[@title='Enter Comment']");
	public static By iconSavePara=By.id("saveButton_parameter");
	public static By iconSaveFunc=By.id("saveButton_function");
	public static By chkboxIncludeCodeSystemVersion=By.xpath("//*[@title='Click to include code system version']");
	public static By topVersionIncludedCodesTable=By.xpath("//table[@id='AppliedCodeTable']/tbody[1]/tr[1]/td[5]/div/div");
	public static By dropdownItemType=By.xpath("//select[@id='availableItemToInsert_ListBox']");
	public static By dropdownIOMode=By.xpath("//select[@id='Mode_listBox']");
	public static By dropdownIOModeDetails=By.xpath("//select[@id='ModeDetails_listBox']");
	public static By closeEditor=By.id("Cancel_button");
	public static By iconDel=By.xpath("//button[@title='Delete']");
	public static By btonpkparameter = By.xpath("//button[@id='Yes_DeleteConfirmationBox']");
	public static By definition_Requireserrormsg = By.xpath("//b[contains(text(),'Please enter definition name.')]");
	public static By definition_spectialChar_errormsg = By.xpath("//b[contains(text(),'Definition +- successfully saved with errors.')]");
	public static By function_Requireserrormsg = By.xpath("//b[contains(text(),'Please enter function name.')]");
	public static By parameter_Requireserrormsg = By.xpath("//b[contains(text(),'Please enter parameter name.')]");
	public static By deleteArgumentbtn = By.xpath("//button[@title='Click to Delete Argument']");
	public static By argumentdeletemsg = By.xpath("//*[contains(text(),'You have selected')]");	
	public static By argumentdeleteNobtn = By.xpath("//button[@id='No_DeleteConfirmationBox']");
	public static By functiondeleteYesbtn = By.xpath("//button[@id='Yes_DeleteConfirmationBox']");	
	public static By functionbox =  By.xpath("//select[@id='funcListBox']");
	public static By commandboxCqlworkspace = By.xpath("//textarea[@id='commentsContent']");
	public static By saveiconCommandboxCQlworkspave = By.xpath("//button[@id='saveButton_GeneralInfo']");
	public static By errormessagegeneralinfo = By.xpath("//b[contains(text(),'Comments can not contain')]");
	public static By sucessmessagegeneralinfo = By.xpath("//b[contains(text(),'general information')]");
	public static By ValuesetEditicon = By.xpath("//button[@title='Click to modify value set']");
	public static By ValuesetProgram = By.xpath("//select[@title='Program selection list']");
	public static By Valuesetappliedvalueset_label = By.xpath("//strong[contains(text(),'Applied Value Sets')]");
	public static By Valuesetappliedvaluesetname_label = By.xpath("//span[@title='Name']");
	public static By Valuesetappliedvaluesetoid_label = By.xpath("//span[@title='OID']");
	public static By Valuesetappliedvaluesetprogram_label = By.xpath("//span[@title='Program']");
	public static By Valuesetappliedvaluesetrelease_label = By.xpath("//span[@title='Release']");
	public static By Valuesetappliedvaluesetedit_label = By.xpath("//span[@title='Edit']");
	public static By Valuesetappliedvaluesetdelete_label = By.xpath("//span[@title='Delete']");
	public static By Valuesetappliedvaluesetcopy_label = By.xpath("//span[@title='Copy']");
	
	public static By appliedvaluesettable = By.xpath("//table[@id='AppliedQDMTable']");
	public static By appliedvaluesettabledata = By.xpath("//span[@id='div2']");
	public static By appliedcodestable = By.xpath("//table[@id='AppliedCodeTable']");
	public static By appliedcodestabledata = By.xpath("//span[@id='div3']");
	
	public static By viewcqllink = By.xpath("//li[@title='View CQL']");
	public static By viewcqlwarningmesg = By.xpath("//*[contains(text(),'ERROR:Could not')]");
	public static By definitionsavedWarningmsg = By.xpath("//b[contains(text(),'Definition ')]");
	public static By parametersavedWarningmsg = By.xpath("//b[contains(text(),'Parameter ')]");
	public static By functionsavedWarningmsg = By.xpath("//b[contains(text(),'Function ')]");
	public static By viewCqlerror = By.xpath("//b[contains(text(),'You are')]");
	

}
